version: '3.9'
services:
  swp-mongoDB:
    restart: unless-stopped
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hammerzon
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  hammerzon:
    image: hammerzon:latest
    environment:
      - MONGODB_URI=mongodb://swp-mongoDB:27017/hammerzon
    ports:
      - '80:80'
    depends_on:
      - swp-mongoDB

volumes:
  db-data:
  mongo-config:
