version: '3.9'
services:
  swp-mongoDB:
    restart: unless-stopped
    image:  mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
