version: '3.8'

services:
    swp-postgres:
        image: postgres:14.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD='changeme1'
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data

